name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  jlab2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab~=2.0 jupyter-packaging~=0.7.9
    - name: Build the extension
      run: |
        pip install .

        jupyter labextension install @jupyter-widgets/jupyterlab-manager .
        jupyter labextension list 2>&1 | grep -ie "@ideonate/jupyter-containds.*OK"
        python -m jupyterlab.browser_check

  jlab3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab~=3.0 jupyter-packaging~=0.7.9
    - name: Build the extension
      run: |
        pip install -e .[test]
        jlpm run eslint:check

        pytest
        jlpm run test

        jupyter labextension list 2>&1 | grep -ie "@ideonate/jupyter-containds.*OK"
